---
- name: update apt packages
  become: true
  apt:
    update_cache: yes

- name: upgrade packages
  become: true
  apt:
    upgrade: true

- name: autoremove
  become: true
  apt:
    autoremove: true

- name: install dependencies
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: create web directory
  file:
    path: ~/application/backend
    state: directory

- name: copy files
  copy:
    src: ../../../../../backend
    dest: ~/application/backend

- name: Install dependencies
  shell: |
    npm install

- name: Start web server
  shell: |
    npm run start
