Description: >
  UdaPeople backend stack.

# Parameters:
#   ID:
#     Description: Unique identifier.
#     Type: String
#     Default: 0

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName: !Sub UdaPeople-${ID}
      GroupName: UdaPeople
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: cf
      ImageId: ami-052efd3df9dad4825
      Tags:
        - Key: Name
          Value: backend-udacity
          # Value: !Sub backend-${ID}
